-- CreateTable price_calculations with all columns including excel capacity fields
CREATE TABLE IF NOT EXISTS "public"."price_calculations" (
    "id" TEXT NOT NULL,
    "productName" TEXT NOT NULL,
    "tagNo" TEXT,
    "grade" TEXT,
    "lotNumber" TEXT,
    "make" TEXT,
    "modelNumber" TEXT,
    "cpu" TEXT,
    "generation" TEXT,
    "ramPresent" BOOLEAN NOT NULL DEFAULT true,
    "ramCapacity" TEXT,
    "excelRamCapacity" TEXT,
    "hddPresent" BOOLEAN NOT NULL DEFAULT true,
    "hdd" TEXT,
    "excelHdd" TEXT,
    "ssdPresent" BOOLEAN NOT NULL DEFAULT true,
    "ssd" TEXT,
    "excelSsd" TEXT,
    "frontPanel" TEXT NOT NULL DEFAULT 'ok',
    "frontPanelCost" DECIMAL(10,2) NOT NULL DEFAULT 0,
    "panel" TEXT NOT NULL DEFAULT 'ok',
    "panelCost" DECIMAL(10,2) NOT NULL DEFAULT 0,
    "screenNonTouch" TEXT NOT NULL DEFAULT 'ok',
    "screenNonTouchCost" DECIMAL(10,2) NOT NULL DEFAULT 0,
    "screenTouch" TEXT NOT NULL DEFAULT 'ok',
    "screenTouchCost" DECIMAL(10,2) NOT NULL DEFAULT 0,
    "hinge" TEXT NOT NULL DEFAULT 'ok',
    "hingeCost" DECIMAL(10,2) NOT NULL DEFAULT 0,
    "touchPad" TEXT NOT NULL DEFAULT 'ok',
    "touchPadCost" DECIMAL(10,2) NOT NULL DEFAULT 0,
    "base" TEXT NOT NULL DEFAULT 'ok',
    "baseCost" DECIMAL(10,2) NOT NULL DEFAULT 0,
    "keyboard" TEXT NOT NULL DEFAULT 'ok',
    "keyboardCost" DECIMAL(10,2) NOT NULL DEFAULT 0,
    "battery" TEXT NOT NULL DEFAULT 'ok',
    "batteryCost" DECIMAL(10,2) NOT NULL DEFAULT 0,
    "repairCost" DECIMAL(10,2) NOT NULL,
    "salePrice" DECIMAL(10,2) NOT NULL,
    "suggestedSalePrice" DECIMAL(10,2) NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "price_calculations_pkey" PRIMARY KEY ("id")
);
